"""Auto-generated dataclasses from LinkML schema.

Do not edit manually. Re-generate with:
    python scripts/gen_models.py <schema.yaml> <output.py>
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class CheckStatus(str, Enum):
    """Status of a check"""

    ok = "ok"
    warning = "warning"
    error = "error"
    version_mismatch = "version-mismatch"
    pending = "pending"


class VersionSource(str, Enum):
    """How the S3 version was determined"""

    doi = "doi"
    assumed_latest = "assumed_latest"


class GithubIssueSubtype(str, Enum):
    """Specific issue type for GitHub mirror checks"""

    tag_missing = "tag-missing"
    head_mismatch = "head-mismatch"
    repo_not_found = "repo-not-found"
    repo_empty = "repo-empty"


class S3VersionIssueSubtype(str, Enum):
    """Specific issue type for S3 version checks"""

    doi_mismatch = "doi-mismatch"
    no_doi = "no-doi"
    blocked = "blocked"


class S3FilesIssueSubtype(str, Enum):
    """Specific issue type for S3 file diff checks"""

    files_missing = "files-missing"
    files_orphaned = "files-orphaned"
    export_missing = "export-missing"


@dataclass
class DatasetsRegistry:
    """Registry of all datasets with their latest snapshot tags. Source of truth
from OpenNeuro GraphQL API."""

    lastChecked: str
    totalCount: int
    latestSnapshots: dict[str, str]


@dataclass
class AllDatasetsSummary:
    """Pre-computed check summaries for all datasets. Generated by SUMMARIZE
process."""

    lastUpdated: str
    datasets: list[DatasetSummary] = field(default_factory=list)


@dataclass
class IssueSubtypes:
    """Per-check issue subtype for filtering and display"""

    github: GithubIssueSubtype | None = None
    s3Version: S3VersionIssueSubtype | None = None
    s3Files: S3FilesIssueSubtype | None = None


@dataclass
class DatasetSummary:
    """Summary of check results for a single dataset"""

    id: str
    status: CheckStatus
    checks: CheckResults
    s3Blocked: bool | None = None
    lastChecked: CheckTimestamps | None = None
    s3FilesAdded: int | None = None
    s3FilesRemoved: int | None = None
    issueSubtypes: IssueSubtypes | None = None
    githubVersion: str | None = None
    s3Version: str | None = None
    latestSnapshotDate: str | None = None


@dataclass
class CheckResults:
    """Status of individual checks"""

    github: CheckStatus
    s3Version: CheckStatus
    s3Files: CheckStatus


@dataclass
class CheckTimestamps:
    """Last check time for each verification"""

    github: str | None = None
    s3Version: str | None = None
    s3Files: str | None = None


@dataclass
class SnapshotIndex:
    """Index of all snapshot tags for a dataset, sorted by creation time"""

    tags: list[str] = field(default_factory=list)


@dataclass
class GitHubStatus:
    """Status of GitHub mirror from git ls-remote"""

    lastChecked: str
    branches: dict[str, str]
    tags: dict[str, str]
    head: str | None = None
    error: str | None = None


@dataclass
class S3Version:
    """Version information from S3's dataset_description.json. Determines which git
tree to compare against for file validation."""

    schemaVersion: str
    lastChecked: str
    accessible: bool
    httpStatus: int | None = None
    datasetDescriptionDOI: str | None = None
    extractedVersion: str | None = None
    versionSource: VersionSource | None = None
    datasetDescriptionMissing: bool | None = None
    doiIdMismatch: bool | None = None
    doiDatasetId: str | None = None
    invalidJson: bool | None = None
    httpError: int | None = None
    requestError: str | None = None
    unexpectedError: str | None = None


@dataclass
class S3FileDiff:
    """Comparison between S3 file listing and git tree. Only created when S3 is
accessible (not 403). Diff semantics: 'what needs to happen to bring S3 into
sync with git.'"""

    schemaVersion: str
    datasetId: str
    snapshotTag: str
    s3Version: str
    checkedAt: str
    status: CheckStatus
    totalS3Files: int
    totalGitFiles: int
    exportMissing: bool | None = None
    added: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    context: list[str] = field(default_factory=list)


@dataclass
class SnapshotMetadata:
    """Immutable metadata about a snapshot from GraphQL. Written once when snapshot
is discovered."""

    hexsha: str
    created: str


@dataclass
class FileList:
    """Complete file listing from git tree. Immutable once created for a tag."""

    count: int
    files: list[str] = field(default_factory=list)
